### ISSUE TITLE
Looks wrong 

### ISSUE THREAD

**Issue by aaron861030** [dimorinny/floating-text-button#6]
It looks like in the attached image after I added into my layout. Tested on real device, also the same. 

    <ru.dimorinny.floatingtextbutton.FloatingTextButton
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:id="@+id/addBtn"
                    android:layout_below="@id/xxx"
                    android:layout_marginTop="20dp"
                    android:layout_centerHorizontal="true"
                    app:floating_background_color="#1976D2"
                    app:floating_left_icon="@drawable/ic_add_white_24dp"
                    app:floating_title="添加"
                    app:floating_title_color="@color/white"/>

![screen shot 2018-03-04 at 12 27 12 pm](https://user-images.githubusercontent.com/30363676/36942185-6eac4b20-1fa7-11e8-9e5f-1d4daaef9de0.png)

The root layout is a relativeLayout. Thanks!

**Comment by aaron861030** [comment]
I found the issue was because I set the appTheme background to white. Changed it, now works. Thanks!

**Comment by sinadalvand** [comment]
@aaron861030 
for solve this issue need change App Theme ?! 
can you explained more?
i have this issue in android 6 and below but in android 7 and 8 is round

how i can fix it ?!
